### ISSUE TITLE
Cannot run application with latest platform-client.jar from arcusplatform

### ISSUE THREAD

**Issue by pupper68k** [arcus-smart-home/arcusandroid#1]
Steps to Reproduce:
- Clone and build arcusplatform.
- Replace arcusandroid/arcusApp/cornea/libs/platform-client-2.0.0-2feabba.jar with newly built platform-client.jar
- Open Android Studio
- Build app 
- Run app 

Expected Behavior:
App opens on connected device

Actual Behaviour:
[Many errors thrown by kotlin compiler](https://cloud.aidanis.online/s/LY53E4kWDzD95Yn)

Problem is reproducible with a virtual android and an LG phone attached via ADB

-------

My current understanding is that any changes made in arcus platform must be manually brought over into the android application by swapping out the platform-client jar file. Please correct if untrue.

**Comment by AndrewX192** [comment]
My guess is that the jar generated by `./gradlew :common:arcus-model:platform-client:jar` is not a fatjar (e.g. one that includes the dependencies). There might be other task in gradle that needs to be run instead of "jar"

**Comment by pupper68k** [comment]
Tried the new shadowJar task for platform-client.
Swapped out the jars for platform client in the android app source tree.
[Here are the new build errors](https://cloud.aidanis.online/s/gmPDHr46m8Ds853)
It looks like a lot of manufacturer specific code is missing from the shadow jar.

I compiled the shadow jar like this: 
``` ./gradlew :common:arcus-model:platform-client:shadowJar  ```
Then I swapped out arcusApp/cornea/libs/platform-client-2.0.0-2feabba.jar with the newly produced platform-client-all.jar.

**Comment by AndrewX192** [comment]
Ah ok - all of that code is intentionally missing. I recommend removing it from the Android app. Nest support is questionably worth looking into given Google's direction, and while Honeywell TCC doesn't seem to have a barrier for signup, it's probably not worth re-implementing at this time.

**Comment by pupper68k** [comment]
Looks like the big culprits are Nest, Hue, Honeywell, and ProMonitoring.

Will begin unraveling that code.

**Comment by eanderso** [comment]
This should now be resolved with https://github.com/arcus-smart-home/arcusandroid/pull/2 merged.
