### ISSUE TITLE
Use platform provided static resource url

### ISSUE THREAD

**Issue by AndrewX192** [arcus-smart-home/arcusandroid#22]
The platform can provide the static resource URL, so instead of needing to configure both the `platform url` and `static resource url`, one could simply configure the `platform url` and rely on whatever the server replies back with, similar to what arcusios does.

**Comment by eanderso** [comment]
The app currently uses this value (from the session object) but has a fallback URL in place. It should be investigated as to why this fallback URL exists and if it can be removed as well as removing this config value from the build.gradle files.
